name: py38
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - openssl=1.1.1k
  - pip=21.1.1
  - python=3.8.8
  - python_abi=3.8
  - setuptools=49.6.0
  - sqlite=3.35.5
  - vc=14.2
  - vs2015_runtime=14.28.29325
  - wheel=0.36.2
  - wincertstore=0.2
  - pip:
    - argon2-cffi==20.1.0
    - async-generator==1.10
    - attrs==20.3.0
    - backcall==0.2.0
    - bleach==3.3.0
    - branca==0.4.2
    - cffi==1.14.5
    - chardet==4.0.0
    - colorama==0.4.4
    - cycler==0.10.0
    - decorator==5.0.7
    - defusedxml==0.7.1
    - entrypoints==0.3
    - folium==0.12.1
    - idna==2.10
    - ipykernel==5.5.4
    - ipython==7.23.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.3
    - jedi==0.18.0
    - jinja2==2.11.3
    - jsonschema==3.2.0
    - jupyter-client==6.1.12
    - jupyter-core==4.7.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.0
    - kiwisolver==1.3.1
    - llvmlite==0.36.0
    - markupsafe==1.1.1
    - matplotlib==3.4.1
    - matplotlib-inline==0.1.2
    - mistune==0.8.4
    - nbclient==0.5.3
    - nbconvert==6.0.7
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - notebook==6.3.0
    - numba==0.53.1
    - numpy==1.20.2
    - open3d==0.12.0
    - opencv-python==4.5.1.48
    - packaging==20.9
    - pandocfilters==1.4.3
    - parso==0.8.2
    - pickleshare==0.7.5
    - pillow==8.2.0
    - prometheus-client==0.10.1
    - prompt-toolkit==3.0.18
    - pycparser==2.20
    - pygments==2.9.0
    - pyparsing==2.4.7
    - pyproj==3.0.1
    - pyrsistent==0.17.3
    - python-dateutil==2.8.1
    - pywin32==300
    - pywinpty==1.0.1
    - pyzmq==22.0.3
    - requests==2.25.1
    - send2trash==1.5.0
    - six==1.16.0
    - terminado==0.9.4
    - testpath==0.4.4
    - tornado==6.1
    - traitlets==5.0.5
    - urllib3==1.26.4
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
